settings:
  data_path: path_to_file
  window_size: 5
  spectralavg: 4
  save_dir: save_path_dir
  exploration_steps: 100 # active learning steps
  num_cycles: 100 # full dkl part
  xi : 0.02  # balances exploration and explitation for EI and qEI
  beta : 0.2 # for ucb
